name: 'chrome_multi'
description: 'A sample command-line application.'
version: '0.0.0'
environment:
  sdk: '>=3.6.0 <4.0.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  msix: '^3.16.7'
dependencies:
  general_lib: '^0.0.63'
  packagex: '^0.0.85'
  mason_logger: '^0.3.1'
  path: '^1.9.0'
executables:
  chrome_multi: 'chrome_multi'
publish_to: 'none'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
packagex:
  name: 'chrome_multi'
  dart_target: 'chrome_multi'
  flutter_target: 'main'
  dart_name: 'chrome_multi'
  flutter_name: 'chrome_multi'
  is_without_platform_name: true
  is_app_auto_clean_up_folder: true
  flutter_commands:
    obfuscate: true
    split-debug-info: '0.0.0'
    build-name: '0.0.0'
    build-number: 1
    split-per-abi: true
    no-tree-shake-icons: true
  project_id: 'azkadev.packagex'
  github_username: 'azkadev'
  github_is_org: false
  flutter_build_arguments: []
  dart_compile_exe_arguments: []
  uploads:
    - platform_type: 'github'
      github_username: 'archivon-apps-stores'
      github_tag: 'release'
      github_is_org: false
      github_repository_name: 'chrome_multi'
    - platform_type: 'supabase'
      supabase_folder_name: 'release'
    - platform_type: 'telegram'
      telegram_chats:
        - chat_id: '@slebew'
          message_thread_id: ''
  packages:
    - dart_target: 'chrome_multi'
      flutter_target: 'main'
      dart_name: 'chrome_multi'
      flutter_name: 'chrome_multi'
      output_name: 'chrome-multi'
msix_config:
  display_name: 'chrome_multi'
  install_certificate: false
