name: chrome_multi
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  packagex: ^0.0.29
  test: ^1.16.0
dependencies:
  galaxeus_lib: ^0.0.89
  mason_logger: ^0.2.8
  path: ^1.8.3

executables:
  chrome_multi: chrome_multi